#!/usr/bin/env python3
"""
Autonomous Tools — Registration Module
Registers a verified tool as a skill pack in functions/<name>/.
"""

import json
import os
import shutil
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

try:
    from hermes_tools import read_file, write_file
except ImportError:
    read_file = write_file = None


def generate_skill_md(tool_name: str, description: str, interface: dict, source: str = "generated") -> str:
    """Generate SKILL.md for the new tool pack."""
    return f"""# {tool_name.replace('-', ' ').title()} — {description}

Auto-generated by autonomous-tools. Source: {source}.

## What it offers
- {description}
- Free/keyless implementation

## Interface
{json.dumps(interface, ensure_ascii=False, indent=2)}

## Usage
```python
from {tool_name.replace('-', '_')} import main  # or the actual function name
result = main(...)
```

## Requirements
- Python 3.11+
- requests (if HTTP)
- No API keys required (uses free/keyless endpoints)

## Generated
- This skill pack was created automatically by autonomous-tools
- Source discovery/creation logged in memory
- Quality verified before registration
"""


def generate_init_py(interface: dict) -> str:
    """Generate __init__.py for the package."""
    func_name = interface.get("function", "main")
    return f'''"""
{interface.get("description", "Auto-generated tool")}
"""
from .{func_name} import {func_name}

__all__ = ["{func_name}"]
'''


def update_config_yaml(skill_name: str, functions_root: str = "A:/OpenDeamon/functions") -> dict:
    """Add skill to config.yaml skills.external_dirs if not present."""
    config_path = Path("A:/OpenDeamon/hermes-home/config.yaml")
    if not config_path.exists():
        return {"updated": False, "error": "config.yaml not found"}

    content = config_path.read_text(encoding="utf-8")

    # Check if external_dirs already includes functions_root
    if "external_dirs:" in content:
        if functions_root.replace("\\", "/") in content.replace("\\", "/"):
            return {"updated": False, "reason": "already in external_dirs"}

    # Find skills section and add
    lines = content.split("\n")
    new_lines = []
    in_skills = False
    added = False

    for line in lines:
        new_lines.append(line)
        if line.strip() == "skills:":
            in_skills = True
        elif in_skills and line.strip().startswith("external_dirs:"):
            # Add our path if not present
            if functions_root not in content:
                indent = len(line) - len(line.lstrip())
                new_lines.append(" " * (indent + 2) + f"- {functions_root}")
                added = True
        elif in_skills and line.strip() and not line.startswith(" "):
            in_skills = False

    if added:
        config_path.write_text("\n".join(new_lines), encoding="utf-8")
        return {"updated": True}

    return {"updated": False, "reason": "skills section not found"}


def register_tool(
    tool_path: str,
    tool_name: str,
    description: str,
    interface: dict,
    source: str = "generated"
) -> dict:
    """
    Register a verified tool as a skill pack.
    tool_path: path to the generated Python file
    tool_name: kebab-case name for the skill directory
    """
    print(f"[register] Registering: {tool_name}")

    skill_dir = Path("A:/OpenDeamon/functions") / tool_name
    skill_dir.mkdir(parents=True, exist_ok=True)

    # 1. Copy main file
    src = Path(tool_path)
    dst = skill_dir / src.name
    shutil.copy2(src, dst)

    # 2. Create SKILL.md
    skill_md = generate_skill_md(tool_name, description, interface, source)
    (skill_dir / "SKILL.md").write_text(skill_md, encoding="utf-8")

    # 3. Create __init__.py if needed (for package imports)
    if not (skill_dir / "__init__.py").exists():
        (skill_dir / "__init__.py").write_text(generate_init_py(interface), encoding="utf-8")

    # 4. Update config.yaml
    config_result = update_config_yaml(tool_name)

    return {
        "registered": True,
        "skill_name": tool_name,
        "skill_dir": str(skill_dir),
        "files": [str(dst), str(skill_dir / "SKILL.md"), str(skill_dir / "__init__.py")],
        "config_update": config_result
    }


def rollback_registration(skill_name: str) -> dict:
    """Remove a registered skill pack (on verification failure)."""
    skill_dir = Path("A:/OpenDeamon/functions") / skill_name
    if skill_dir.exists():
        shutil.rmtree(skill_dir)
        return {"rolled_back": True, "skill_name": skill_name}
    return {"rolled_back": False, "reason": "not found"}


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("tool_path")
    parser.add_argument("tool_name")
    parser.add_argument("--desc", default="")
    parser.add_argument("--interface", default="{}")
    parser.add_argument("--source", default="generated")
    parser.add_argument("--rollback", action="store_true")
    args = parser.parse_args()

    interface = json.loads(args.interface)

    if args.rollback:
        result = rollback_registration(args.tool_name)
    else:
        result = register_tool(args.tool_path, args.tool_name, args.desc, interface, args.source)

    print(json.dumps(result, ensure_ascii=False, indent=2))